version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: yes
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 100
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      runas: root
      timeout: 100
